#
# FreeSCI/DOS Makefile
#
# 19991220              rink            created this file
#
#
TARGET  :       scigraphics.a

FILES   =       con_io.o con_font.o graphics_dgfx.o graphics.o font.o \
                mcursor.o input.o window.o menubar.o  engine_graphics.o \
		graphics_png.o

CC	= gcc
CFLAGS	= -g -c -I../include -I../.. -D_DOS -DHAVE_LIBPNG -DHAVE_UNISTD_H \
	  -DHAVE_DGFX

clean:
		del *.o *.a

scigraphics.a:  ${FILES}
		ar r scigraphics.a ${FILES}
