#define HAVE_ERRNO_H 1
#define HAVE_FCNTL_H 1
#define HAVE_FNMATCH_H 1
#define HAVE_ISBLANK 1
#define HAVE_LIMITS_H 1
#define HAVE_MEMCHR 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE_USLEEP 1
#define PACKAGE "freesci"
#define SIZEOF_INT 4
#define SIZEOF_LONG 4
#define SIZEOF_SHORT 2
#define STDC_HEADERS 1
#define X_DISPLAY_MISSING 1
#define YYTEXT_POINTER 1
#define VERSION "0.3.5-devel"
