#
# FreeSCI/DOS Makefile
#
# 19991220              rink            created this file
#
#
TARGET  :       scisound.a

FILES   =       oldmidi.o sfx_save.o sound.o soundserver_dos.o
		
CC	= gcc
CFLAGS	= -g -c -I../include -I../.. -D_DOS -DHAVE_UNISTD_H -DHAVE_LIBPNG

clean:
		del *.o *.a

scisound.a:     ${FILES}
		ar r scisound.a ${FILES}
