/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 25
#define YY_END_OF_BUFFER 26
static yyconst short int yy_accept[314] =
    {   0,
       24,   24,   26,   24,   23,   23,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   23,
       23,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   22,   24,    1,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       21,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   21,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,

       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   13,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   13,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,

       24,   24,    3,   24,   24,   24,   24,   24,   24,   19,
       24,   24,   24,   24,   24,   24,   24,    9,   24,   24,
       24,   24,   24,   24,   24,    3,   17,   17,   24,   20,
       20,   24,   19,   24,   24,   24,   24,   24,    8,   24,
        9,   24,   24,   24,   10,   24,   24,   11,   24,   24,
       24,   24,   24,   24,   24,   24,    8,   24,   18,   18,
       10,   24,   11,   24,   24,   12,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   12,   24,    7,
       24,   24,   24,   24,   24,    6,   24,   24,   24,   24,
       15,    7,   24,    5,   24,   24,   24,    6,   24,   14,

       16,    5,   24,    2,   24,    2,   24,   24,   24,   24,
        4,    4,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    1,    6,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    8,    1,    1,
        9,    1,    1,    1,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       11,    1,   12,    1,   13,    1,   14,   15,   16,   17,

       18,   19,   20,   21,   22,   10,   23,   24,   25,   26,
       27,   28,   10,   29,   30,   31,   32,   33,   34,   35,
       36,   37,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[38] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[350] =
    {   0,
        0,    0, 1038,    0,   36,   38,    0,   41,   54,   66,
       54,   65,   25,   21,   35,   46,   58,   67,    0,   92,
       94, 1034,   97, 1010,  110,   47,   64,   74,   98,   78,
       90,   91,  104,  101,  100,  103,  110, 1039,  136,    0,
      108,  116,  120,  125,  126,  128,  140,  130,  151,  135,
      137,  139,  141,  169,  178,  162,  144,  166,  168,  176,
      171, 1018,  180,  186,  185,  177,  188,  189,  192,  218,
      231,  182,  208,  148,  212,  224,  231, 1005,  243,  231,
     1001, 1010,  225, 1012,  190, 1011,  269,  227, 1004,  238,
      234, 1003,  997, 1004,  256,  281,  996, 1002, 1001, 1006,

     1002,  996,  246,  997,  992,  995,  240,  989,  250,  996,
      987,  982,  979,  294,  307,  979,  979,  983,  994,  988,
      975,  295,  981,  308,  980,  977,  985,  977,  978,  982,
      969,  979,  334,  966,  974,  976,  969,  974,  973,  271,
      959,  266,  318,  958,  278,  968,  956,  958,  961,  960,
      942,  949,  949,  948,  936,  919,  912,  919,  915,  320,
      927,  911,  907,  321,  901,  889,  331,  886,  335,  898,
      875,  874,  879,  882,  339,  870,  858,  322,  852,  862,
      345,  354,  348,  859,  362,  364,  853,  366,  390,  839,
      846,  829,  367,  825,  368,  403,  823,  371,  325,  372,

      822,  416,  429,  380,  837,  805,  819,  810,  441,  454,
      800,  324,  805,  384,  466,  791,  479,  492,  404,  417,
      504,  377,  430,  517,  798,  530,    0,  807,  442,    0,
      791,  760,  542,  773,  756,  764,  757,  554,  567,  737,
      579,  455,  769,  591,  604,  760,  616,  629,  722,  467,
      641,  480,  735,  733,  718,  493,  654,  728,    0,  729,
      666,  429,  678,  505,  690,  703,  518,  715,  531,  707,
      687,  543,  728,  555,  454,  568,  736,  743,  755,  768,
      580,  780,  592,  695,  793,  806,  605,  814,  492,  817,
      530,  824,  836,  849,  617,  861,  681,  874,  882,  542,

        0,  889,  901,  914,  683,  926,  630,  642,  938,  951,
      964,  976, 1039,  705,  699,  692,  687,  684,  683,  680,
      675,  672,  671,  668,  663,  660,  659,  656,  635,  634,
      610,  609,  585,  584,  573,  572,  399,  384,  352,  350,
      313,  278,  258,  227,  209,  180,  138,   81,   59
    } ;

static yyconst short int yy_def[350] =
    {   0,
      313,    1,  313,  314,  314,  313,  315,  316,  317,  316,
       10,   10,   10,   10,   10,   10,   10,   10,  314,  314,
      313,  315,  318,   10,  317,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,  313,  318,  314,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,  314,  319,   10,   10,   10,   10,   10,
       10,  314,   10,   10,  314,   10,   10,   10,   10,  319,
      320,   10,   10,   10,   10,   10,   10,  314,   10,  314,
      314,  314,   10,  314,   10,  314,  320,   10,  314,   10,
       10,  314,  314,  314,  314,  321,  314,  314,  314,  314,

      314,  314,   10,  314,   10,  314,   10,  314,   10,  314,
      314,  314,  314,  321,  322,  314,  314,  314,  314,  314,
      314,   10,  314,   10,  314,   10,  314,  314,  314,  314,
      314,  314,  322,  314,  314,  314,  314,  314,  314,   10,
      314,  314,  314,  314,   10,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  323,  314,  314,  314,  314,  314,  314,  324,  314,
      314,  314,  314,  314,  314,  325,  314,  314,  314,  314,

      314,  323,  326,  314,  327,  314,  328,  314,  324,  329,
      314,  314,  314,  314,  330,  314,  325,  331,  314,  314,
      332,  314,  314,  333,  314,  326,  327,  327,  314,  328,
      328,  314,  329,  314,  314,  314,  314,  330,  334,  314,
      331,  314,  335,  332,  336,  314,  333,  337,  314,  314,
      338,  314,  314,  314,  314,  314,  334,  314,  335,  335,
      336,  314,  337,  314,  338,  339,  314,  340,  314,  314,
      314,  314,  341,  314,  314,  314,  314,  339,  340,  342,
      314,  343,  314,  314,  341,  344,  314,  314,  314,  314,
      314,  342,  343,  345,  314,  346,  314,  344,  314,  314,

      314,  345,  346,  347,  314,  347,  314,  314,  348,  348,
      349,  349,    0,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313
    } ;

static yyconst short int yy_nxt[1077] =
    {   0,
        4,    5,    6,    7,    4,    8,    8,    4,    4,    8,
        9,    4,    4,   10,    8,   11,   12,    8,    8,   13,
        8,    8,    8,    8,   14,    8,    8,   15,   16,    8,
       17,    8,   18,    8,    8,    8,    8,   20,   21,   21,
       21,   19,   19,   31,   19,   23,   24,   32,   19,   19,
       24,   19,   19,   19,   19,   19,   33,   19,   19,  312,
       24,   19,   19,   34,   19,   19,   19,   19,   41,   19,
       23,   24,   24,   19,   19,   35,   19,   19,   19,   24,
       27,  311,   29,   24,   36,   28,   30,   42,   37,   43,
       24,   26,   24,   20,   21,   21,   21,   19,   19,   24,

       19,   19,   44,   24,   19,   19,   46,   19,   19,   19,
       19,   19,   45,   19,   19,   24,   24,   19,   19,   49,
       19,   40,   48,   24,   47,   24,   24,   53,   24,   24,
       50,   52,   56,   24,   51,   24,   19,   54,  306,   19,
       19,   24,   57,   19,   55,   24,   19,   19,   19,   58,
       24,   24,   62,   24,   59,   24,   64,   60,   61,   63,
       24,   66,   24,   65,   24,   24,   24,   67,   68,   24,
       54,   90,   73,   24,   69,   72,   24,   55,   19,   70,
      304,   19,   19,   19,   19,   19,   19,   24,   19,   19,
       19,   24,   74,   24,   75,   76,   24,   79,   80,   81,

       84,   24,   24,   82,   86,   24,   77,   24,   83,  302,
       85,   24,   88,   24,   24,   24,  105,   24,   19,   70,
       89,   19,   19,   19,   19,   19,   19,  298,   19,   19,
       19,   19,   19,   24,   19,   19,   92,   24,   19,   19,
       91,   19,   19,   93,   95,   97,  110,   98,  107,   24,
       24,   96,   24,  103,   99,  109,   24,   95,  294,   24,
      100,  122,  128,   24,   96,   24,  126,  142,   24,   19,
       19,   24,   19,   19,  143,   24,   19,   19,  292,   19,
       19,   19,  114,  158,   19,   19,   19,   19,   19,   19,
      163,   19,   19,   19,   19,  114,   24,   19,   19,   19,

       19,   19,   19,   24,   19,   19,   19,   19,   19,  142,
       19,   19,  140,  286,   19,   19,  143,   19,   19,  160,
       24,  160,  181,  161,  161,  161,  161,  199,  199,  182,
      222,  222,  185,   24,   19,   19,  188,   19,   19,  186,
      195,   19,   19,  189,   19,   19,  181,  196,  235,  204,
      280,  236,  278,  182,   19,  202,  205,   19,   19,   19,
       19,   19,   19,  185,   19,   19,   19,  188,  214,  195,
      186,  207,  220,  223,  189,  215,  196,  207,  207,  221,
      224,  204,  246,  246,  266,  214,  207,  207,  205,  207,
       19,  209,  215,   19,   19,   19,   19,   19,   19,  263,

       19,   19,   19,   19,  217,  242,   19,   19,   19,   19,
       19,   19,  243,   19,   19,   19,   19,  202,  220,   19,
       19,   19,   19,   19,   19,  221,   19,   19,   19,   19,
       19,  223,   19,   19,  275,  275,   19,   19,  224,   19,
       19,   19,  209,  250,   19,   19,   19,   19,   19,   19,
      251,   19,   19,   19,   19,   19,  242,   19,   19,  289,
      289,   19,   19,  243,   19,   19,   19,  238,  250,   19,
       19,   19,   19,   19,   19,  251,   19,   19,   19,   19,
      217,  267,   19,   19,   19,   19,   19,   19,  268,   19,
       19,   19,   19,   19,  272,   19,   19,  301,  301,   19,

       19,  273,   19,   19,   19,  244,  276,   19,   19,   19,
       19,   19,   19,  277,   19,   19,   19,   19,  247,  267,
       19,   19,   19,   19,   19,   19,  268,   19,   19,   19,
       19,   19,  281,   19,   19,  291,  291,   19,   19,  282,
       19,   19,   19,   19,  272,   19,   19,  300,  300,   19,
       19,  273,   19,   19,   19,  238,  287,   19,   19,   19,
       19,   19,   19,  288,   19,   19,   19,   19,   19,  276,
       19,   19,  261,  259,   19,   19,  277,   19,   19,   19,
       19,  281,   19,   19,  257,  248,   19,   19,  282,   19,
       19,   19,  244,  295,   19,   19,   19,   19,   19,   19,

      296,   19,   19,   19,   19,   19,  287,   19,   19,  245,
      241,   19,   19,  288,   19,   19,   19,  247,  295,   19,
       19,   19,   19,   19,   19,  296,   19,   19,   19,   19,
       19,  308,   19,   19,  239,  233,   19,   19,  309,   19,
       19,   19,  265,  308,   19,   19,   19,   19,   19,   19,
      309,   19,   19,   19,   19,   19,  230,   19,   19,  227,
      226,   19,   19,  218,   19,   19,   19,   19,  210,   19,
       19,  203,  133,   19,   19,  115,   19,   19,   19,   19,
       87,   19,   19,   71,   39,   19,   19,   25,   19,   19,
       19,  265,   24,   19,   19,   19,   19,   19,   19,   22,

       19,   19,   19,   19,   19,   19,   19,   19,  307,  305,
       19,   19,  297,   19,   19,   19,  279,  284,   19,   19,
       19,   19,   19,   19,  283,   19,   19,   19,   19,  285,
      260,   19,   19,   19,   19,   19,   19,  290,   19,   19,
       19,  291,  291,   19,   19,  274,   19,   19,  271,  270,
       19,   19,  269,   19,   19,   19,  279,  264,   19,   19,
       19,   19,   19,   19,  262,   19,   19,   19,   19,   19,
      260,   19,   19,  258,  256,   19,   19,  255,   19,   19,
       19,  293,  254,   19,   19,   19,   19,   19,   19,  253,
       19,   19,   19,   19,  285,  252,   19,   19,   19,   19,

       19,   19,  231,   19,   19,   19,   19,   19,  228,   19,
       19,  249,  240,   19,   19,  299,   19,   19,  290,  300,
      300,  237,  291,  291,   19,   19,  234,   19,   19,  232,
      231,   19,   19,  229,   19,   19,   19,  293,  228,   19,
       19,   19,   19,   19,   19,  225,   19,   19,   19,   19,
       19,  219,   19,   19,  216,  213,   19,   19,  212,   19,
       19,   19,  303,  211,   19,   19,   19,   19,   19,   19,
      208,   19,   19,   19,   19,   19,  206,   19,   19,  201,
      200,   19,   19,  299,   19,   19,  198,  300,  300,   19,
       19,  197,   19,   19,  194,  193,   19,   19,  192,   19,

       19,   19,  303,  191,   19,   19,   19,   19,   19,   19,
      190,   19,   19,   19,   19,   19,  187,   19,   19,  184,
      183,   19,   19,  180,   19,   19,   19,   19,  179,   19,
       19,  178,  177,   19,   19,  176,   19,   19,   19,  310,
      175,   19,   19,   19,   19,   19,   19,  174,   19,   19,
       19,   19,  310,  173,   19,   19,   19,   19,   19,   19,
      172,   19,   19,   19,   19,   19,  171,   19,   19,  170,
      169,   19,   19,  168,   19,   19,   19,   19,  167,   19,
       19,  166,  165,   19,   19,  164,   19,   19,  162,  159,
      157,  156,  155,  154,  153,  152,  151,  150,  149,  148,

      147,  146,  145,  144,  141,  139,  138,  137,  136,  135,
      134,  132,  131,  130,  129,  127,  125,  124,  123,  121,
      120,  119,  118,  117,  116,  113,  112,  111,  108,  106,
      104,  102,  101,   94,   78,   24,   38,  313,    3,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313
    } ;

static yyconst short int yy_chk[1077] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    6,
        6,    8,    8,   13,    8,    8,   14,   14,    8,    8,
       13,    8,    8,    8,    9,    9,   15,    9,    9,  349,
       15,    9,    9,   16,    9,    9,   10,   10,   26,   10,
       10,   16,   26,   10,   10,   17,   10,   10,   10,   11,
       11,  348,   12,   17,   18,   11,   12,   27,   18,   27,
       12,   10,   18,   20,   20,   21,   21,   23,   23,   28,

       23,   23,   28,   30,   23,   23,   30,   23,   23,   23,
       25,   25,   29,   25,   25,   31,   32,   25,   25,   33,
       25,   25,   32,   29,   31,   35,   34,   37,   36,   33,
       34,   36,   41,   41,   35,   37,   39,   39,  347,   39,
       39,   42,   42,   39,   39,   43,   39,   39,   39,   43,
       44,   45,   47,   46,   44,   48,   49,   45,   46,   48,
       50,   50,   51,   49,   52,   47,   53,   51,   52,   57,
       54,   74,   57,   74,   53,   56,   49,   54,   55,   55,
      346,   55,   55,   55,   55,   55,   55,   56,   55,   55,
       55,   58,   58,   59,   59,   60,   61,   63,   64,   65,

       67,   60,   66,   65,   69,   63,   61,   72,   66,  345,
       68,   64,   72,   67,   68,   85,   85,   69,   70,   70,
       73,   70,   70,   70,   70,   70,   70,  344,   70,   70,
       70,   71,   71,   73,   71,   71,   76,   75,   71,   71,
       75,   71,   71,   77,   79,   80,   91,   80,   88,   76,
       83,   79,   88,   83,   80,   90,   77,   95,  343,   91,
       80,  103,  109,   90,   95,  107,  107,  142,   79,   87,
       87,  103,   87,   87,  142,  109,   87,   87,  342,   87,
       87,   96,   96,  140,   96,   96,   96,   96,   96,   96,
      145,   96,   96,   96,  114,  114,  140,  114,  114,  114,

      114,  114,  114,  145,  114,  114,  114,  115,  115,  124,
      115,  115,  122,  341,  115,  115,  124,  115,  115,  143,
      122,  160,  164,  143,  143,  160,  160,  178,  178,  164,
      199,  199,  167,  124,  133,  133,  169,  133,  133,  167,
      175,  133,  133,  169,  133,  133,  181,  175,  212,  183,
      340,  212,  339,  181,  182,  182,  183,  182,  182,  182,
      182,  182,  182,  185,  182,  182,  182,  188,  193,  195,
      185,  186,  198,  200,  188,  193,  195,  186,  186,  198,
      200,  204,  222,  222,  338,  214,  186,  186,  204,  186,
      189,  189,  214,  189,  189,  189,  189,  189,  189,  337,

      189,  189,  189,  196,  196,  219,  196,  196,  196,  196,
      196,  196,  219,  196,  196,  196,  202,  202,  220,  202,
      202,  202,  202,  202,  202,  220,  202,  202,  202,  203,
      203,  223,  203,  203,  262,  262,  203,  203,  223,  203,
      203,  209,  209,  229,  209,  209,  209,  209,  209,  209,
      229,  209,  209,  209,  210,  210,  242,  210,  210,  275,
      275,  210,  210,  242,  210,  210,  215,  215,  250,  215,
      215,  215,  215,  215,  215,  250,  215,  215,  215,  217,
      217,  252,  217,  217,  217,  217,  217,  217,  252,  217,
      217,  217,  218,  218,  256,  218,  218,  289,  289,  218,

      218,  256,  218,  218,  221,  221,  264,  221,  221,  221,
      221,  221,  221,  264,  221,  221,  221,  224,  224,  267,
      224,  224,  224,  224,  224,  224,  267,  224,  224,  224,
      226,  226,  269,  226,  226,  291,  291,  226,  226,  269,
      226,  226,  233,  233,  272,  233,  233,  300,  300,  233,
      233,  272,  233,  233,  238,  238,  274,  238,  238,  238,
      238,  238,  238,  274,  238,  238,  238,  239,  239,  276,
      239,  239,  336,  335,  239,  239,  276,  239,  239,  241,
      241,  281,  241,  241,  334,  333,  241,  241,  281,  241,
      241,  244,  244,  283,  244,  244,  244,  244,  244,  244,

      283,  244,  244,  244,  245,  245,  287,  245,  245,  332,
      331,  245,  245,  287,  245,  245,  247,  247,  295,  247,
      247,  247,  247,  247,  247,  295,  247,  247,  247,  248,
      248,  307,  248,  248,  330,  329,  248,  248,  307,  248,
      248,  251,  251,  308,  251,  251,  251,  251,  251,  251,
      308,  251,  251,  251,  257,  257,  328,  257,  257,  327,
      326,  257,  257,  325,  257,  257,  261,  261,  324,  261,
      261,  323,  322,  261,  261,  321,  261,  261,  263,  263,
      320,  263,  263,  319,  318,  263,  263,  317,  263,  263,
      265,  265,  316,  265,  265,  265,  265,  265,  265,  315,

      265,  265,  265,  266,  266,  314,  266,  266,  305,  297,
      266,  266,  284,  266,  266,  268,  268,  271,  268,  268,
      268,  268,  268,  268,  270,  268,  268,  268,  273,  273,
      260,  273,  273,  273,  273,  273,  273,  277,  273,  273,
      273,  277,  277,  278,  278,  258,  278,  278,  255,  254,
      278,  278,  253,  278,  278,  279,  279,  249,  279,  279,
      279,  279,  279,  279,  246,  279,  279,  279,  280,  280,
      243,  280,  280,  240,  237,  280,  280,  236,  280,  280,
      282,  282,  235,  282,  282,  282,  282,  282,  282,  234,
      282,  282,  282,  285,  285,  232,  285,  285,  285,  285,

      285,  285,  231,  285,  285,  285,  286,  286,  228,  286,
      286,  225,  216,  286,  286,  288,  286,  286,  290,  288,
      288,  213,  290,  290,  292,  292,  211,  292,  292,  208,
      207,  292,  292,  206,  292,  292,  293,  293,  205,  293,
      293,  293,  293,  293,  293,  201,  293,  293,  293,  294,
      294,  197,  294,  294,  194,  192,  294,  294,  191,  294,
      294,  296,  296,  190,  296,  296,  296,  296,  296,  296,
      187,  296,  296,  296,  298,  298,  184,  298,  298,  180,
      179,  298,  298,  299,  298,  298,  177,  299,  299,  302,
      302,  176,  302,  302,  174,  173,  302,  302,  172,  302,

      302,  303,  303,  171,  303,  303,  303,  303,  303,  303,
      170,  303,  303,  303,  304,  304,  168,  304,  304,  166,
      165,  304,  304,  163,  304,  304,  306,  306,  162,  306,
      306,  161,  159,  306,  306,  158,  306,  306,  309,  309,
      157,  309,  309,  309,  309,  309,  309,  156,  309,  309,
      309,  310,  310,  155,  310,  310,  310,  310,  310,  310,
      154,  310,  310,  310,  311,  311,  153,  311,  311,  152,
      151,  311,  311,  150,  311,  311,  312,  312,  149,  312,
      312,  148,  147,  312,  312,  146,  312,  312,  144,  141,
      139,  138,  137,  136,  135,  134,  132,  131,  130,  129,

      128,  127,  126,  125,  123,  121,  120,  119,  118,  117,
      116,  113,  112,  111,  110,  108,  106,  105,  104,  102,
      101,  100,   99,   98,   97,   94,   93,   92,   89,   86,
       84,   82,   81,   78,   62,   24,   22,    3,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "config.l"
#define INITIAL 0
/***************************************************************************
 config.l (C) 1999 Christoph Reichenbach, TU Darmstadt


 This program may be modified and copied freely according to the terms of
 the GNU general public license (GPL), as long as the above copyright
 notice and the licensing information contained herein are preserved.

 Please refer to www.gnu.org for licensing details.

 This work is provided AS IS, without warranty of any kind, expressed or
 implied, including but not limited to the warranties of merchantibility,
 noninfringement, and fitness for a specific purpose. The author will not
 be held liable for any damage caused by this work or derivatives of it.

 By using this source code, you agree to the licensing terms as stated
 above.


 Please contact the maintainer for bug reports or inquiries.

 Current Maintainer:

    Christoph Reichenbach (CJR) [jameson@linuxgames.com]

***************************************************************************/
#line 29 "config.l"
#include <engine.h>
#include <gfx_system.h>
#include <gfx_tools.h>
#include <gfx_resource.h>
#include <sci_conf.h>

#ifdef _MSC_VER
#  include <ctype.h>
#  include <direct.h>

#  define strcasecmp stricmp
#  define PATH_MAX 255

#endif

config_entry_t *conf;
int cur_section=0; /* Size-1 and current section in conf */
char *exported_conf_path; /* Path which the config file was found in */
int dospath; /* Use dos-style paths? */

typedef struct {
	char *name;
	int value;
} name_value_pair;

static int
_parse_name(char *name, name_value_pair* nvps, char *what, int oldval); /* Parses a string with a name value pair */

static gfx_driver_t *
_parse_gfx_driver(char *s); /* Parses a graphics driver */

static name_value_pair valid_modes[] = {
	{"default", GFXR_DITHER_MODE_D16},
	{"dither", GFXR_DITHER_MODE_D16},
	{"dither16", GFXR_DITHER_MODE_D16},
	{"dither_16", GFXR_DITHER_MODE_D16},
	{"dither-16", GFXR_DITHER_MODE_D16},
	{"d16", GFXR_DITHER_MODE_D16},
	{"flat", GFXR_DITHER_MODE_F256},
	{"interpol", GFXR_DITHER_MODE_F256},
	{"interpolate", GFXR_DITHER_MODE_F256},
	{"dither256", GFXR_DITHER_MODE_D256},
	{"dither_256", GFXR_DITHER_MODE_D256},
	{"d256", GFXR_DITHER_MODE_D256},
	{0, 0} /* Terminator */
};

static name_value_pair yesno[] = {
	{"yes", 1},
	{"no", 0},
	{"1", 1},
	{"0", 0},
	{"ok", 1},
	{"enable", 1},
	{"disable", 0},
	{"activate", 1},
	{"deactivate", 0},
	{"+", 1},
	{"-", 0},
	{"on", 1},
	{"off", 0},
	{0, 0}
};

static name_value_pair dither_pattern[] = {
	{"scaled", GFXR_DITHER_PATTERN_SCALED},
	{"unscaled", GFXR_DITHER_PATTERN_1},
	{"one", GFXR_DITHER_PATTERN_1},
	{"1", GFXR_DITHER_PATTERN_1},
	{0, 0}
};

static name_value_pair dirty_strategy[] = {
	{"1", GFXOP_DIRTY_FRAMES_ONE},
	{"one", GFXOP_DIRTY_FRAMES_ONE},
	{"cluster", GFXOP_DIRTY_FRAMES_CLUSTERS},
	{"clusters", GFXOP_DIRTY_FRAMES_CLUSTERS},
	{0, 0}
};

static name_value_pair brush_mode[] = {
	{"scaled", GFX_BRUSH_MODE_SCALED},
	{"ellipse", GFX_BRUSH_MODE_ELLIPSES},
	{"ellipses", GFX_BRUSH_MODE_ELLIPSES},
	{"rnd_ellipses", GFX_BRUSH_MODE_RANDOM_ELLIPSES},
	{"rnd-ellipses", GFX_BRUSH_MODE_RANDOM_ELLIPSES},
	{"random_ellipses", GFX_BRUSH_MODE_RANDOM_ELLIPSES},
	{"random-ellipses", GFX_BRUSH_MODE_RANDOM_ELLIPSES},
	{"morerandom", GFX_BRUSH_MODE_MORERANDOM},
	{"more-random", GFX_BRUSH_MODE_MORERANDOM},
	{"more_random", GFX_BRUSH_MODE_MORERANDOM},
	{0, 0}
};

static name_value_pair filter_mode[] = {
	{"none", GFX_XLATE_FILTER_NONE},
	{"linear", GFX_XLATE_FILTER_LINEAR},
	{"bilinear", GFX_XLATE_FILTER_LINEAR},
	{"bi-linear", GFX_XLATE_FILTER_LINEAR},
	{0, 0}
};

static name_value_pair line_mode[] = {
	{"correct", GFX_LINE_MODE_CORRECT},
	{"normal", GFX_LINE_MODE_CORRECT},
	{"fast", GFX_LINE_MODE_FAST},
	{"fine", GFX_LINE_MODE_FINE},
	{"thin", GFX_LINE_MODE_FINE},
	{0, 0}
};

#line 846 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 147 "config.l"


#line 1000 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 314 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1039 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 149 "config.l"
{
	++yytext; /* Get over opening bracket */

	++cur_section; /* Start new section */

	/* Create new entry... */
	conf = realloc(conf, sizeof(config_entry_t) * (cur_section + 1));

	/* ...and initialize it */
	memcpy(&(conf[cur_section]), &(conf[0]), sizeof(config_entry_t));
	if (conf[0].console_log)
		conf[cur_section].console_log = strdup (conf[0].console_log);

	/* Copy the gfx system init strings */
	if (conf[cur_section].gfx_config) {
		conf[cur_section].gfx_config = malloc(sizeof(gfx_option_t *) * conf[0].gfx_config_nr);
		memcpy(&(conf[cur_section].gfx_config), &(conf[0].gfx_config),
		       sizeof(gfx_option_t *) * conf[0].gfx_config_nr);
	}

	while (isspace(*yytext))
		yytext++;

	conf[cur_section].name = strdup(yytext);
	conf[cur_section].name[strlen(yytext)-1] = 0; /* Terminate string at "]" */
	conf[cur_section].resource_dir = strdup(".");

	if (dospath)
		conf[cur_section].work_dir = strdup(exported_conf_path);
	else {
		char *tmp = malloc(strlen(exported_conf_path) + 1 + strlen(yytext));
		strcpy(tmp, exported_conf_path);
		strcat(tmp, "/");
		strcat(tmp, conf[cur_section].name);

		conf[cur_section].work_dir = tmp;
		scimkdir(tmp, 0700); /* Make sure that the directory exists. */
		/* This will be checked later, for the current game. */
	}
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 190 "config.l"
{
	yytext = strchr(yytext, '=') + 1;

	while (isspace(*yytext))
		yytext++;
	conf[cur_section].gfx_options.pic0_dither_mode = 
		_parse_name(yytext, valid_modes, "color mode", conf[cur_section].gfx_options.pic0_dither_mode);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 199 "config.l"
{ /* Deprecated: For backward compatibility */
	yytext = strchr(yytext, '=') + 1;

	while (isspace(*yytext))
		yytext++;
	conf[cur_section].gfx_options.pic0_dither_mode =
		_parse_name(yytext, valid_modes, "color mode", conf[cur_section].gfx_options.pic0_dither_mode);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 208 "config.l"
{
	yytext = strchr(yytext, '=') + 1;

	while (isspace(*yytext))
		yytext++;
	conf[cur_section].gfx_options.pic0_dither_pattern =
		_parse_name(yytext, dither_pattern, "SCI0 pic dither pattern", conf[cur_section].gfx_options.pic0_dither_pattern);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 217 "config.l"
{
	yytext = strchr(yytext, '=') + 1;

	while (isspace(*yytext))
		yytext++;
	conf[cur_section].gfx_options.pic0_brush_mode =
		_parse_name(yytext, brush_mode, "SCI0 pic brush mode", conf[cur_section].gfx_options.pic0_brush_mode);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 226 "config.l"
{
	yytext = strchr(yytext, '=') + 1;

	while (isspace(*yytext))
		yytext++;
	conf[cur_section].gfx_options.pic0_line_mode =
		_parse_name(yytext, line_mode, "SCI0 pic line mode", conf[cur_section].gfx_options.pic0_line_mode);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 235 "config.l"
{
	yytext = strchr(yytext, '=') + 1;

	while (isspace(*yytext))
		yytext++;
	conf[cur_section].gfx_options.dirty_frames =
		_parse_name(yytext, dirty_strategy, "dirty strategy", conf[cur_section].gfx_options.dirty_frames);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 244 "config.l"
{
	yytext = strchr(yytext, '=') + 1;

	while (isspace(*yytext))
		yytext++;
	conf[cur_section].gfx_options.pic0_unscaled =
		!_parse_name(yytext, yesno, "pic0 scaling", !conf[cur_section].gfx_options.pic0_unscaled);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 253 "config.l"
{
	yytext = strchr(yytext, '=') + 1;

	while (isspace(*yytext))
		yytext++;
	conf[cur_section].gfx_options.pic_xlate_filter =
		_parse_name(yytext, filter_mode, "pic filter", conf[cur_section].gfx_options.pic_xlate_filter);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 262 "config.l"
{
	yytext = strchr(yytext, '=') + 1;

	while (isspace(*yytext))
		yytext++;
	conf[cur_section].gfx_options.text_xlate_filter =
		_parse_name(yytext, filter_mode, "text filter", conf[cur_section].gfx_options.text_xlate_filter);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 271 "config.l"
{
	yytext = strchr(yytext, '=') + 1;

	while (isspace(*yytext))
		yytext++;
	conf[cur_section].gfx_options.view_xlate_filter =
		_parse_name(yytext, filter_mode, "view filter", conf[cur_section].gfx_options.view_xlate_filter);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 280 "config.l"
{
	yytext = strchr(yytext, '=') + 1;

	while (isspace(*yytext))
		yytext++;
	conf[cur_section].gfx_options.cursor_xlate_filter =
		_parse_name(yytext, filter_mode, "cursor filter", conf[cur_section].gfx_options.cursor_xlate_filter);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 289 "config.l"
{
	yytext = strchr(yytext, '=') + 1;

	while (isspace(*yytext))
		yytext++;
	conf[cur_section].mouse =
		!_parse_name(yytext, yesno, "mouse", !conf[cur_section].mouse);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 298 "config.l"
{
	int val;
	yytext = strchr(yytext, '=') + 1;

	while (isspace(*yytext))
		yytext++;

	val = atoi(yytext);
	if (val < 0) {
		printf("No negative values allowed for pic buffer size\n");
	} else conf[cur_section].gfx_options.buffer_pics_nr = val;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 311 "config.l"
{
	int val;
	yytext = strchr(yytext, '=') + 1;

	while (isspace(*yytext))
		yytext++;

	val = atoi(yytext);
	if (val < 0) {
		printf("No negative values allowed for animation_delay\n");
	} else conf[cur_section].animation_delay = val;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 324 "config.l"
{ /***** End of graphics *****/

	yytext = strchr(yytext, '=') + 1;

	while (isspace(*yytext))
		yytext++;

	conf[cur_section].version = version_parse(yytext);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 334 "config.l"
{
	yytext = strchr (yytext, '=') + 1;

	while (isspace(*yytext))
		yytext++;

	if (conf[cur_section].console_log)
		free (conf[cur_section].console_log);
	conf[cur_section].console_log = (char *) malloc (strlen (yytext)+1);
	strcpy (conf[cur_section].console_log, yytext);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 346 "config.l"
if (cur_section) {
	yytext = strchr(yytext, '=') + 1;
	while (isspace(*yytext))
		yytext++;

	free(conf[cur_section].resource_dir);

	conf[cur_section].resource_dir = strdup(yytext);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 357 "config.l"
{
	yytext = strchr(yytext, '=') + 1;

	while (isspace(*yytext))
		yytext++;

	conf[cur_section].gfx_driver = _parse_gfx_driver(yytext);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 366 "config.l"
{
        yytext = strchr(yytext, '=') + 1;

        while (isspace(*yytext))
                yytext++;

	strcpy (conf[cur_section].debug_mode, yytext);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 375 "config.l"
{
        char *p=yytext;
        char *p2;

        yytext = strchr(yytext, '.');
        *yytext++ = 0;
        if (!strcasecmp (p, conf->gfx_driver->name)) {
                int newcfg;

                p = yytext;
                yytext = strchr(yytext, '=');
                *yytext++ = 0;

                p2 = yytext-2;                    /* trim right spaces */
                while (p2 > p && isspace (*p2))
                        *p2-- = 0;

                while (isspace(*yytext))
                        yytext++;

                p2=yytext+strlen (yytext);        /* trim right spaces */
                while (p2 > p && isspace (*p2))
                *p2-- = 0;

                newcfg = (conf[cur_section].gfx_config_nr)++;

                if (newcfg)
                conf[cur_section].gfx_config = realloc(conf[cur_section].gfx_config,
			(newcfg + 1) * sizeof(gfx_option_t *));
		else
		        conf[cur_section].gfx_config = malloc(conf[cur_section].gfx_config_nr * sizeof(gfx_option_t *));

                conf[cur_section].gfx_config[newcfg].option = strdup(p);
                conf[cur_section].gfx_config[newcfg].value = strdup(yytext);
        }
}
	YY_BREAK
case 22:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 415 "config.l"
/* Ignore comments */
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 417 "config.l"
/* Eat whitespace */
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 419 "config.l"
{
        yy_delete_buffer( YY_CURRENT_BUFFER );
        yyterminate();
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 424 "config.l"
printf("Unrecognized option: %s\n", yytext);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 426 "config.l"
ECHO;
	YY_BREAK
#line 1438 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 314 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 314 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 313);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 426 "config.l"


int
yywrap()
{
        return 1; /* no further input */
}


int
config_init(config_entry_t **_conf, char *conffile)
{
	char *homedir = getenv("HOME");
	char *conf_path;

	conf = malloc(sizeof(config_entry_t));

/**** Default config: */
	conf->gfx_options.buffer_pics_nr = 0;
	conf->gfx_options.correct_rendering = 1;
	conf->gfx_options.pic0_unscaled = 0;
	conf->gfx_options.pic0_dither_mode = GFXR_DITHER_MODE_D16;
	conf->gfx_options.pic0_dither_pattern = GFXR_DITHER_PATTERN_SCALED;
	conf->gfx_options.pic0_brush_mode = GFX_BRUSH_MODE_RANDOM_ELLIPSES;
	conf->gfx_options.pic0_line_mode = GFX_LINE_MODE_CORRECT;
	conf->gfx_options.cursor_xlate_filter = GFX_XLATE_FILTER_NONE;
	conf->gfx_options.view_xlate_filter = GFX_XLATE_FILTER_NONE;
	conf->gfx_options.pic_xlate_filter = GFX_XLATE_FILTER_NONE;
	conf->gfx_options.text_xlate_filter = GFX_XLATE_FILTER_NONE;
	conf->gfx_options.dirty_frames = GFXOP_DIRTY_FRAMES_CLUSTERS;

	conf->gfx_driver = gfx_find_driver(NULL);

	conf->mouse = 1;

	conf->version = 0;

	conf->animation_delay = 500;
	conf->console_log = NULL;
	conf->debug_mode [0] = '\0';
	conf->name = NULL;
	conf->resource_dir = NULL;
	conf->work_dir = NULL;
	conf->gfx_config = NULL;
	conf->gfx_config_nr = 0;
/**** Default config ends */


	if (conffile) {
		exported_conf_path = (char *) malloc(PATH_MAX + 1);
		getcwd(exported_conf_path, PATH_MAX+1);

		conf_path = strdup(conffile); /* Use config file if supplied */
	} else {
		if (!homedir) { /* We're probably not under UNIX if this happens */

			conf_path = strdup(FREESCI_CONFFILE_DOS); /* Use DOS config style */

			exported_conf_path = (char *) malloc(PATH_MAX + 1);
			getcwd(exported_conf_path, PATH_MAX+1);

			dospath = 1; /* Use DOS-style paths */

		} else {

			/* So we've got a home directory */
			if (chdir(homedir)) {
				fprintf(stderr,"Warning: Could not enter home directory!\n");
				return 1;
			}

			if (chdir(FREESCI_GAMEDIR))
				if (scimkdir(FREESCI_GAMEDIR, 0700)) {

					fprintf(stderr,"Warning: Could not enter/create ~/"FREESCI_GAMEDIR"\n");
					return 1;
				}

			conf_path = malloc(strlen(homedir) + 3 + strlen(FREESCI_GAMEDIR) + strlen(FREESCI_CONFFILE));
			strcpy(conf_path, homedir);
			strcat(conf_path, "/");
			strcat(conf_path, FREESCI_GAMEDIR);

			exported_conf_path = strdup(conf_path);

			strcat(conf_path, "/");
			strcat(conf_path, FREESCI_CONFFILE);

			dospath = 0; /* Use UN*X-style paths */
		}
	} /* !conffile */


	if (!(yyin = fopen(conf_path, "r"))) {
		printf("No configuration file found; using defaults.\n");
		*_conf = conf; /* Set the result variable */
		free(conf_path);
		free(exported_conf_path);
		return 1;
	}

	printf("Parsing config file...\n");

	yylex(); /* Parse the file */

	free(conf_path);
	free(exported_conf_path);

	*_conf = conf; /* Store the result */
	return cur_section + 1;
}


void
config_free(config_entry_t **conf, int entries)
{
	int i;

	if ((*conf)->console_log)
		free((*conf)->console_log);

	for (i = 1; i < entries; i++) {
		free ((*conf)[i].name);
		free ((*conf)[i].work_dir);
		if ((*conf)[i].resource_dir)
			free ((*conf)[i].resource_dir);
		if ((*conf)[i].console_log)
			free((*conf)[i].console_log);

		if ((*conf)[i].gfx_config) {
			int j;

			for (j = 0; j < (*conf)[i].gfx_config_nr; j++) {
				free ((*conf)[i].gfx_config[j].option);
				free ((*conf)[i].gfx_config[j].value);
			}

			free((*conf)[i].gfx_config);
		}
	}

	free (*conf);
}


static int
_parse_name(char *name, name_value_pair *nvps, char *what, int oldval)
{
	int i = 0;

	while (nvps[i].name) {
		if (0 == strcasecmp(name, nvps[i].name))
			return nvps[i].value;

		i++;
	}

	printf("Invalid %s mode %s\n", what, name);

	return oldval;
}


static gfx_driver_t *
_parse_gfx_driver(char *driver_name)
{
	gfx_driver_t *retval = gfx_find_driver(driver_name);

	if (retval)
		return retval;
	/* not found - return default */

	printf ("Unknown graphics driver %s\n", driver_name);
	return conf->gfx_driver;
}
